"""Fraud signal definitions — all named signals with weights."""
HIGH_AMOUNT_NO_POLICE = "HIGH_AMOUNT_NO_POLICE_REPORT"
NEW_POLICY_QUICK_CLAIM = "NEW_POLICY_QUICK_CLAIM"
HIGH_PRIOR_CLAIMS = "HIGH_PRIOR_CLAIMS"
MULTIPLE_ADDRESS_CHANGES = "MULTIPLE_ADDRESS_CHANGES"
EXTERNAL_AGENT_HIGH_CLAIM = "EXTERNAL_AGENT_HIGH_CLAIM"
NO_WITNESS_MULTI_CAR = "NO_WITNESS_MULTI_CAR"
EXCESS_SUPPLEMENTS = "EXCESS_SUPPLEMENTS"
POLICY_HOLDER_AT_FAULT = "POLICY_HOLDER_AT_FAULT"
WEEKEND_NO_WITNESS = "WEEKEND_NO_WITNESS"
NEW_POLICY_SHORT_DURATION = "NEW_POLICY_SHORT_DURATION"
OLD_VEHICLE_HIGH_PRICE = "OLD_VEHICLE_HIGH_PRICE"
RAPID_CLAIM_FILING = "RAPID_CLAIM_FILING"
HIGH_DRIVER_RATING = "HIGH_DRIVER_RATING"
URBAN_NO_EVIDENCE = "URBAN_NO_EVIDENCE"
REPEATED_CLAIM_PATTERN = "REPEATED_CLAIM_PATTERN"

SIGNAL_WEIGHTS = {
    HIGH_AMOUNT_NO_POLICE: 12, NEW_POLICY_QUICK_CLAIM: 10, HIGH_PRIOR_CLAIMS: 10,
    MULTIPLE_ADDRESS_CHANGES: 8, EXTERNAL_AGENT_HIGH_CLAIM: 8, NO_WITNESS_MULTI_CAR: 8,
    EXCESS_SUPPLEMENTS: 7, POLICY_HOLDER_AT_FAULT: 6, WEEKEND_NO_WITNESS: 6,
    NEW_POLICY_SHORT_DURATION: 9, OLD_VEHICLE_HIGH_PRICE: 7, RAPID_CLAIM_FILING: 9,
    HIGH_DRIVER_RATING: 5, URBAN_NO_EVIDENCE: 6, REPEATED_CLAIM_PATTERN: 10,
}
